-- Snowflake Silver and Gold Layer Schema Initialization
-- Creates cleaned and aggregated tables for analytics

USE DATABASE FLOWGUARD_DB;

-- Create Silver schema (cleaned, deduplicated data)
CREATE SCHEMA IF NOT EXISTS SILVER;
USE SCHEMA SILVER;

-- Silver Orders Table: Cleaned and deduplicated orders
CREATE TABLE IF NOT EXISTS ORDERS_CLEAN (
    -- Core fields from Bronze
    INGESTION_ID VARCHAR(200) PRIMARY KEY,
    EVENT_ID VARCHAR(100) NOT NULL,
    ORDER_ID VARCHAR(100) NOT NULL,
    USER_ID INTEGER NOT NULL,
    ITEM_ID INTEGER NOT NULL,
    ITEM_NAME VARCHAR(255),
    PRICE DECIMAL(10, 2) NOT NULL,
    STATUS VARCHAR(50),
    EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    PARTITION_DATE DATE NOT NULL,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    SOURCE_TOPIC VARCHAR(100),
    PRODUCER_SERVICE VARCHAR(100),
    
    -- Data Quality flags
    IS_VALID BOOLEAN NOT NULL,
    IS_DUPLICATE BOOLEAN NOT NULL,
    VALIDATION_ERRORS VARCHAR(500),
    
    -- Silver metadata
    PROCESSED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Silver Clicks Table: Cleaned and deduplicated clicks
CREATE TABLE IF NOT EXISTS CLICKS_CLEAN (
    -- Core fields from Bronze
    INGESTION_ID VARCHAR(200) PRIMARY KEY,
    EVENT_ID VARCHAR(100) NOT NULL,
    USER_ID INTEGER NOT NULL,
    ITEM_ID INTEGER,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    SESSION_ID VARCHAR(100),
    EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    PARTITION_DATE DATE NOT NULL,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    SOURCE_TOPIC VARCHAR(100),
    PRODUCER_SERVICE VARCHAR(100),
    
    -- Data Quality flags
    IS_VALID BOOLEAN NOT NULL,
    IS_DUPLICATE BOOLEAN NOT NULL,
    VALIDATION_ERRORS VARCHAR(500),
    
    -- Silver metadata
    PROCESSED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create Gold schema (aggregated business metrics)
CREATE SCHEMA IF NOT EXISTS GOLD;
USE SCHEMA GOLD;

-- Gold Daily GMV Metrics: Daily aggregated revenue metrics
CREATE TABLE IF NOT EXISTS DAILY_GMV_METRICS (
    DATE DATE PRIMARY KEY,
    TOTAL_REVENUE DECIMAL(15, 2) NOT NULL,
    ORDER_COUNT INTEGER NOT NULL,
    UNIQUE_USERS INTEGER NOT NULL,
    AVG_ORDER_VALUE DECIMAL(10, 2) NOT NULL,
    CALCULATED_AT TIMESTAMP_NTZ NOT NULL
);

-- Verify tables created
USE SCHEMA SILVER;
SHOW TABLES IN SILVER;

USE SCHEMA GOLD;
SHOW TABLES IN GOLD;
